In [1]:
%pylab inline

from tqdm import tqdm_notebook as tqdm
import requests
import pickle
import re
import itertools
import functools
import collections
import string
import time
from bs4 import BeautifulSoup
from sortedcontainers import SortedList # http://www.grantjenks.com/docs/sortedcontainers/sortedlist.html#sortedlist

from adventlib import *

YEAR = 2022
DAY = int('01')

submit1, submit2 = generate_submits(YEAR, DAY)

while True:
  try:
    raw_input = get_input(YEAR, DAY)
    break
  except Exception as e:
    print(e)
    time.sleep(1)

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib
Please don't repeatedly request this endpoint before it unlocks! The calendar countdown is synchronized with the server time; the link will be enabled on the calendar the instant this puzzle becomes available.

Please don't repeatedly request this endpoint before it unlocks! The calendar countdown is synchronized with the server time; the link will be enabled on the calendar the instant this puzzle becomes available.

Please don't repeatedly request this endpoint before it unlocks! The calendar countdown is synchronized with the server time; the link will be enabled on the calendar the instant this puzzle becomes available.

Please don't repeatedly request this endpoint before it unlocks! The calendar countdown is synchronized with the server time; the link will be enabled on the calendar the instant this puzzle becomes available.

Please don't 

In [ ]:
lines, groups = linesplit("""

""".strip())

In [2]:
lines, groups = linesplit(raw_input, verbose=True)

2237 lines
241 groups
>>>
5557
6663
3952
...


In [3]:
a = []
for i in groups:
  a.append(amap(int, i))
a

[array([5557, 6663, 3952, 4750, 2271, 6653, 4406, 4256, 6871, 6720, 6248,
        4518, 4987]),
 array([3931, 8484, 8418, 7221, 6057, 7458, 7336, 8299, 5058]),
 array([7862, 4603, 4837, 5209, 1427, 3766, 4454, 3664, 9580]),
 array([6306, 4457, 5653, 4466, 5949, 7420, 2789, 3053, 2060, 4009, 1580,
        5870]),
 array([2128, 5160, 6167, 2810, 7342, 7388, 3945, 2653, 4605, 8023, 3736]),
 array([40312]),
 array([ 8527,  4368,  1291,  1159,  2869, 10302,  8489]),
 array([3268, 4846, 4747, 8406, 4839, 4459, 6374, 3271, 3072, 1600]),
 array([2279, 2628, 4570, 1688, 2989, 6512, 5511, 5544, 1312, 6497]),
 array([32986, 21583]),
 array([5607, 1597, 7704, 6719, 7585, 6676, 1192, 5987, 7336, 2079, 7280]),
 array([4148]),
 array([6518, 7660, 2690, 6461, 7436, 4628, 5750, 5493, 4000, 7290]),
 array([ 3774,  5553,  2325,  6203, 10506,  7826, 11499]),
 array([6237, 6275, 7370, 6287, 6289, 3980, 2487, 2940, 3886, 5351, 5284,
        5486]),
 array([2847, 4282, 1406, 2164, 4119, 2192, 2714, 3284, 371

In [5]:
b = amap(sum, a)

In [6]:
b

array([67852, 62262, 45402, 53612, 53957, 40312, 37005, 44882, 39530,
       54569, 59762,  4148, 57926, 47686, 61872, 49497, 18803, 49082,
       37241, 56764, 48416, 53270, 52433, 40129, 34309, 55945, 48172,
       68164, 49054, 40909,  7781, 56491, 44652, 21711, 52036, 46745,
       63465, 48858, 16430, 53447, 53661, 56481, 52268, 48663,  1175,
       44492, 52428, 51425, 56825, 53656, 37017, 58686, 44031, 38549,
       52802, 30443, 61005, 55384, 56490, 39028, 47723, 47672, 11627,
       46489, 57620, 53765, 26968, 41240, 56955, 35462, 41708, 40480,
       52203, 38593, 46644, 54446, 49616, 59211, 38703, 69894, 17416,
       40643, 58134, 53675, 55490, 43421, 65598, 49757, 51242, 53281,
       48828, 51181, 57674, 57392, 58144, 40182, 48153, 54355, 43503,
       49599, 58086, 48033, 45901, 47795, 60484, 57723, 60212, 55253,
       45287, 32281, 42171, 42054, 48417, 55449, 34284, 58985, 47147,
       51106, 42566, 58368, 49200, 46343, 48781, 27639, 54702, 36616,
       45157, 13709,

In [8]:
b[argmax(b)]

70509

In [9]:

submit1(_)

True

In [13]:
sum(b[argsort(b)[-3:]])

208567

In [14]:
submit2(_)

True

In [23]:
x = å(groups, functools.partial(amap, int), sum)
max(x), sum(sorted(x)[-3:])

(70509, 208567)