In [1]:
import numpy as np
from numpy import *
import matplotlib
from matplotlib import pyplot as plt
from tqdm.auto import tqdm
import requests
import pickle
import re
import itertools
import functools
import collections
import string
import time
from bs4 import BeautifulSoup
from sortedcontainers import SortedList # http://www.grantjenks.com/docs/sortedcontainers/sortedlist.html#sortedlist

from adventlib import *

YEAR = 2022
DAY = int('08')

submit1, submit2 = generate_submits(YEAR, DAY)

while True:
  try:
    raw_input = get_input(YEAR, DAY)
    break
  except Exception as e:
    print(e)
    time.sleep(1)

In [61]:
lines, groups = linesplit("""
30373
25512
65332
33549
35390
""".strip())

In [65]:
lines, groups = linesplit(raw_input, verbose=True)

99 lines
1 groups
>>>
101002200302221033023303143134003020403131311534441424251301311211314032120023113231033031121022011
000000201330102222312340313324430424413214435242113342242434514432041413213343304030120232213020102
010000203232213031433114342021403232235333514333553111322134215441434143114041342040010222003200011
...


In [66]:

def lines_as_matrix_nm(lines):
  assert len(set(map(len, lines))) == 1
  a = np.array(list(map(list, lines)), dtype='<U1')
  return a.shape[0], a.shape[1], a


def lines_as_matrix(lines):
  return lines_as_matrix_nm(lines)[2]


def lines_as_digit_matrix(lines):
  return vectorize(int)(lines_as_matrix(lines))

In [67]:
a = lines_as_digit_matrix(lines)

In [55]:
b = ones_like(a, dtype=bool)

In [8]:
a

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [69]:
n, m = a.shape

In [26]:
b = ones_like(a, dtype=bool)
b[1:n-1,1:m-1] = False


for i in range(1, n-1):
  for j in range(1,m-1):
    b[i, j] |= all(a[i, 0:j] < a[i, j])
    b[i, j] |= all(a[i, j+1:m] < a[i, j])
    b[i, j] |= all(a[0:i,j] < a[i, j])
    b[i, j] |= all(a[i+1:n, j] < a[i, j])
    # b[i, j] |= all(a[i, j:m-1] < a[i, j+1:m])
    # b[i, j] |= all(a[1:i, j] < a[0:i-1, j])
    # b[i, j] |= all(a[i:n-1, j] < a[i+1:n, j])
    # b[i, j] |= all(a[i, 1:j] < a[i, 0:j-1])
    # b[i, j] |= all(a[i, 1:j] < a[i, 0:j-1])
    # b[i, j] |= all(a[i, 1:j] < a[i, 0:j-1])
b

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True, False, False, ...,  True, False,  True],
       [ True,  True, False, ..., False, False,  True],
       ...,
       [ True, False, False, ...,  True, False,  True],
       [ True, False, False, ...,  True, False,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [27]:
sum(b)

1849

In [28]:
submit1(_)

Submitting 1849...


True

In [70]:
b = zeros_like(a, dtype=int)
# b[1:n-1,1:m-1] = False


for i in range(1, n-1):
  for j in range(1,m-1):
    p = 1
    
    x = (a[i, 0:j] < a[i, j])[::-1]
    # print(x)
    y = where(x == False)[0]
    if len(y) > 0:
      p *= y[0] + 1
    else:
      p *= len(x)
    # print(p)
    
    x = (a[i, j+1:m] < a[i, j])
    y = where(x == False)[0]
    if len(y) > 0:
      p *= y[0] + 1
    else:
      p *= len(x)
    
    x = (a[0:i, j] < a[i, j])[::-1]
    y = where(x == False)[0]
    if len(y) > 0:
      p *= y[0] + 1
    else:
      p *= len(x)
    
    x = (a[i+1:n, j] < a[i, j])
    y = where(x == False)[0]
    if len(y) > 0:
      p *= y[0] + 1
    else:
      p *= len(x)
    
    b[i, j] = p
    # print(x, )
    
    
    # b[i, j] |= all(a[i, j+1:m] < a[i, j])
    # b[i, j] |= all(a[0:i,j] < a[i, j])
    # b[i, j] |= all(a[i+1:n, j] < a[i, j])
    # b[i, j] |= all(a[i, j:m-1] < a[i, j+1:m])
    # b[i, j] |= all(a[1:i, j] < a[0:i-1, j])
    # b[i, j] |= all(a[i:n-1, j] < a[i+1:n, j])
    # b[i, j] |= all(a[i, 1:j] < a[i, 0:j-1])
    # b[i, j] |= all(a[i, 1:j] < a[i, 0:j-1])
    # b[i, j] |= all(a[i, 1:j] < a[i, 0:j-1])
b

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  1,  1, ...,  8,  1,  0],
       [ 0, 30,  1, ...,  1,  8,  0],
       ...,
       [ 0,  2,  1, ...,  2,  1,  0],
       [ 0,  2,  1, ...,  1,  3,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [71]:
max(b.max(axis=0))

201600

In [72]:
submit2(_)

Submitting 201600...


True