In [1]:
import numpy as np
from numpy import *
import matplotlib
from matplotlib import pyplot as plt
from tqdm.auto import tqdm
import requests
import pickle
import re
import itertools
import functools
import collections
import string
import time
from bs4 import BeautifulSoup
from sortedcontainers import SortedList # http://www.grantjenks.com/docs/sortedcontainers/sortedlist.html#sortedlist

import multiprocess
# with multiprocess.Pool(processes=8) as pool:
#   for i in pool.imap_unordered(f, a):
#     print(i)

from adventlib.common import *
# n, m, a = lines_as_matrix_nm(lines)
# a = lines_as_matrix(lines)
# a = lines_as_digit_matrix(lines)
# chunks = split_iter_by_start_indices(a, indices)
# chunks = split_iter_by_bools(a, bools)

# from adventlib.point_2d import *
# from adventlib.point_3d import *

YEAR = 2022
DAY = int('20')

submit1, submit2 = generate_submits(YEAR, DAY)

while True:
  try:
    raw_input = get_input(YEAR, DAY)
    break
  except Exception as e:
    print(e)
    time.sleep(1)

In [81]:
lines, groups = linesplit("""
1
2
-3
3
-2
0
4
""".strip())

In [89]:
lines, groups = linesplit(raw_input, verbose=True)

5000 lines
1 groups
>>>
-2446
159
2372
...


In [90]:
a = amap(int, lines)

In [75]:
A = c_[a[:, np.newaxis], np.arange(len(a))[:, np.newaxis]]

n = len(a)

for i in range(len(a)):
  delta = A[i, 0]
  if delta > 0:
    delta = delta % (n - 1)
    A[:, 1] = (A[:, 1] + n - A[i, 1]) % n
  elif delta < 0:
    delta = -(-delta % (n - 1))
    A[:, 1] = (A[:, 1] + n - A[i, 1] - 1 + n) % n
  
  pos = A[i, 1]
  newpos = ((pos + delta + n) % n + n) % n
  # print(A[i, 0], pos, newpos, A)
  
  if pos == newpos:
    continue
  
  if newpos > pos:
    A[logical_and(A[:, 1] > pos, A[:, 1] <= newpos), 1] -= 1
  
  if newpos < pos:
    A[logical_and(A[:, 1] < pos, A[:, 1] >= newpos), 1] += 1
  
  A[i, 1] = newpos
  
#   b = []
#   for i in argsort(A[:, 1]):
#     b.append(A[i, 0])
#   b = np.array(b, dtype=int)
#   b
  
#   print('fin', A, b)

In [76]:
b = []
for i in argsort(A[:, 1]):
  b.append(A[i, 0])
b = np.array(b, dtype=int)
b

array([ -332, -4961,  6583, ..., -8062,  3081, -5155])

In [77]:
i = where(b == 0)[0][0]
i

704

In [78]:
b[(i + arange(1000, 4000, 1000)) % n]

array([ 8370, -8315,  4859])

In [79]:
sum(_)

4914

In [80]:
submit1(sum(_))

Submitting 4914...


True

In [52]:
SUBMITTED_ANSWERS

{(2022, 20, 1, 757): False}

In [91]:
A = c_[a[:, np.newaxis], np.arange(len(a))[:, np.newaxis]]
A[:, 0] *= 811589153

n = len(a)

for it in range(10):
  for i in range(len(a)):
    delta = A[i, 0]
    if delta > 0:
      delta = delta % (n - 1)
      A[:, 1] = (A[:, 1] + n - A[i, 1]) % n
    elif delta < 0:
      delta = -(-delta % (n - 1))
      A[:, 1] = (A[:, 1] + n - A[i, 1] - 1 + n) % n

    pos = A[i, 1]
    newpos = ((pos + delta + n) % n + n) % n
    # print(A[i, 0], pos, newpos, A)

    if pos == newpos:
      continue

    if newpos > pos:
      A[logical_and(A[:, 1] > pos, A[:, 1] <= newpos), 1] -= 1

    if newpos < pos:
      A[logical_and(A[:, 1] < pos, A[:, 1] >= newpos), 1] += 1

    A[i, 1] = newpos
  
#   b = []
#   for i in argsort(A[:, 1]):
#     b.append(A[i, 0])
#   b = np.array(b, dtype=int)
#   b
  
#   print('fin', A, b)

In [92]:
b = []
for i in argsort(A[:, 1]):
  b.append(A[i, 0])
b = np.array(b, dtype=int)
b

array([ 7056767685335, -5147909997479,  4867911739694, ...,
        3431398938884,  7300244431235, -7236128888148])

In [93]:
i = where(b == 0)[0][0]
i

4365

In [94]:
b[(i + arange(1000, 4000, 1000)) % n]

array([ 5205532827342, -4838694530186,  7606213541916])

In [95]:
sum(_)

7973051839072

In [96]:
submit2(_)

Submitting 7973051839072...


True