In [1]:
%pylab inline

from tqdm import tqdm_notebook as tqdm
import requests
import pickle
import re
import itertools
import functools
import collections
import string
import time
from bs4 import BeautifulSoup

from adventlib import *

YEAR = 2020
DAY = 10

submit1, submit2 = generate_submits(YEAR, DAY)

while True:
    try:
        raw_input = get_input(YEAR, DAY)
        break
    except Exception as e:
        print(e)
        time.sleep(1)

Populating the interactive namespace from numpy and matplotlib


In [2]:
lines, groups = linesplit("""

""".strip())

In [3]:
lines, groups = linesplit(raw_input, verbose=True)

114 lines
1 groups
>>>
178
135
78
...


In [4]:
a = amap(int, lines)
a = r_[a, 0, max(a) + 3]

In [5]:
b = a[argsort(a)]

In [6]:
c = b[1:] - b[:-1]
c

array([1, 1, 1, 1, 3, 3, 1, 1, 1, 3, 3, 1, 1, 1, 3, 1, 1, 3, 3, 1, 1, 3,
       3, 3, 1, 1, 1, 1, 3, 1, 3, 3, 1, 1, 1, 3, 3, 1, 3, 1, 1, 1, 3, 1,
       1, 1, 3, 3, 1, 1, 1, 1, 3, 1, 1, 3, 1, 1, 1, 1, 3, 3, 1, 1, 3, 1,
       1, 3, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 3,
       3, 1, 1, 1, 3, 3, 1, 1, 1, 3, 1, 1, 1, 3, 1, 1, 3, 1, 1, 1, 1, 3,
       3, 3, 1, 1, 3])

In [7]:
sum(c == 1) * sum(c == 3)

3000

In [8]:
submit1(3000)

True

In [11]:
m = max(b)

In [16]:
b

array([  0,   1,   2,   3,   4,   7,  10,  11,  12,  13,  16,  19,  20,
        21,  22,  25,  26,  27,  30,  33,  34,  35,  38,  41,  44,  45,
        46,  47,  48,  51,  52,  55,  58,  59,  60,  61,  64,  67,  68,
        71,  72,  73,  74,  77,  78,  79,  80,  83,  86,  87,  88,  89,
        90,  93,  94,  95,  98,  99, 100, 101, 102, 105, 108, 109, 110,
       113, 114, 115, 118, 119, 120, 121, 122, 125, 128, 129, 130, 131,
       132, 135, 136, 137, 138, 139, 142, 143, 144, 145, 148, 151, 152,
       153, 154, 157, 160, 161, 162, 163, 166, 167, 168, 169, 172, 173,
       174, 177, 178, 179, 180, 181, 184, 187, 190, 191, 192, 195])

In [19]:
dp = np.zeros(m + 1, dtype=object)

dp[0] = 1

for i in range(0, m + 1):
    for j in b:
        if j > i and j - i <= 3 and j <= m:
            dp[j] += dp[i]

dp

array([1, 1, 2, 4, 7, 0, 0, 7, 0, 0, 7, 7, 14, 28, 0, 0, 28, 0, 0, 28, 28,
       56, 112, 0, 0, 112, 112, 224, 0, 0, 224, 0, 0, 224, 224, 448, 0, 0,
       448, 0, 0, 448, 0, 0, 448, 448, 896, 1792, 3136, 0, 0, 3136, 3136,
       0, 0, 3136, 0, 0, 3136, 3136, 6272, 12544, 0, 0, 12544, 0, 0,
       12544, 12544, 0, 0, 12544, 12544, 25088, 50176, 0, 0, 50176, 50176,
       100352, 200704, 0, 0, 200704, 0, 0, 200704, 200704, 401408, 802816,
       1404928, 0, 0, 1404928, 1404928, 2809856, 0, 0, 2809856, 2809856,
       5619712, 11239424, 19668992, 0, 0, 19668992, 0, 0, 19668992,
       19668992, 39337984, 0, 0, 39337984, 39337984, 78675968, 0, 0,
       78675968, 78675968, 157351936, 314703872, 550731776, 0, 0,
       550731776, 0, 0, 550731776, 550731776, 1101463552, 2202927104,
       3855122432, 0, 0, 3855122432, 3855122432, 7710244864, 15420489728,
       26985857024, 0, 0, 26985857024, 26985857024, 53971714048,
       107943428096, 0, 0, 107943428096, 0, 0, 107943428096, 10794342809

In [20]:
dp[-1]

193434623148032

In [21]:
submit2(_)

True