In [6]:
%pylab inline

from tqdm import tqdm_notebook as tqdm
import requests
import pickle
import re
import itertools
import functools
import collections
import string
import time
from bs4 import BeautifulSoup

from adventlib import *

YEAR = 2020
DAY = 13

submit1, submit2 = generate_submits(YEAR, DAY)

while True:
    try:
        raw_input = get_input(YEAR, DAY)
        break
    except Exception as e:
        print(e)
        time.sleep(1)

Populating the interactive namespace from numpy and matplotlib


In [ ]:
lines, groups = linesplit("""

""".strip())

In [7]:
lines, groups = linesplit(raw_input, verbose=True)

2 lines
1 groups
>>>
1007125
13,x,x,41,x,x,x,x,x,x,x,x,x,569,x,29,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,19,x,x,x,23,x,x,x,x,x,x,x,937,x...


In [8]:
st = int(lines[0])

a = amap(int, re.findall('\d+', lines[1]))

In [28]:
for i in range(1000):
    x = st + i
    w = a[where(x % a == 0)[0]]
#     print(i, x, w)
    if w:
        print(i)
        break
        

5


<ipython-input-28-16fcf6fff54b>:5: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if w:


In [29]:
i * w[0]

2845

In [31]:
submit1(_)

True

In [26]:
w

array([2])

In [ ]:
submit1()

In [17]:
def gcd(a, b):
    if a < b:
        return gcd(b, a)
    if a % b == 0:
        return b
    return gcd(b, a % b)

gcd(12, 63)

3

In [18]:
x = 1
for i in a:
    x = x * i // gcd(x, i)
    print(x)

13
533
303277
8795033
167105627
3843429421
3601293367477
133247854596649
2265213528143033


In [19]:
st

1007125

In [ ]:
x - st

In [34]:
a = []
for i in re.findall(r'[^,]+', lines[1]):
    if i == 'x':
        a.append(0)
    else:
        a.append(int(i))

a

[13,
 0,
 0,
 41,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 569,
 0,
 29,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 19,
 0,
 0,
 0,
 23,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 937,
 0,
 0,
 0,
 0,
 0,
 37,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 17]

In [40]:
!pip3 install z3

     |████████████████████████████████| 1.4 MB 2.0 MB/s eta 0:00:01
Using legacy 'setup.py install' for z3, since package 'wheel' is not installed.
    Running setup.py install for z3 ... done
You should consider upgrading via the '/Users/abra/projects/jupyter/.venv/bin/python3 -m pip install --upgrade pip' command.


In [44]:
b = []
for i, j in enumerate(a):
    if j != 0:
        b.append((i, j))
b

[(0, 13),
 (3, 41),
 (13, 569),
 (15, 29),
 (32, 19),
 (36, 23),
 (44, 937),
 (50, 37),
 (61, 17)]

In [41]:
import z3

In [58]:
x = z3.Int('x')
s = z3.Solver()

s.add(x > 0)

for i, j in b[:4]:
    s.add((x + i) % j == 0)
    
s.check()

sat

In [59]:
s.model()[x]

5784441

In [70]:
z3.solve(x > 0, x % 13 == 0, x % 41 == 38)

[x = 325]


In [71]:
def up(a1, b1, a2, b2):
    if a1 < a2:
        return up(a2, b2, a1, b1)
    
    x = b1
    while x % a2 != b2:
        x += a1
    
    a = a1 * a2 // gcd(a1, a2)
    return a, x

In [75]:
up(1, 0, 13, 0)

(13, 0)

In [76]:
a0 = 1
b0 = 0

for i, j in b:
    a0, b0 = up(a0, b0, j, (j - i) % j)
    print(a0, b0)

13 0
533 325
303277 22178
8795033 5784441
167105627 155300002
3843429421 1826356272
3601293367477 1731369595722
133247854596649 88162410415170
2265213528143033 487905974205117


In [80]:
b = np.array(b)
b

array([[  0,  13],
       [  3,  41],
       [ 13, 569],
       [ 15,  29],
       [ 32,  19],
       [ 36,  23],
       [ 44, 937],
       [ 50,  37],
       [ 61,  17]])

In [81]:
b0 % np.array(b[:, 1])

array([  0,  38, 556,  14,   6,  10, 893,  24,   7])

In [82]:
submit2(b0)

True

(303277, 207129)